### ISSUE TITLE
Fatal error on Woocommerce 3.5.x

### ISSUE THREAD

**Issue by moisb** [WPprodigy/woocommerce-external-product-embed#25]
when inserting the shortcode the post breaks with the following fatal error message:

`Fatal error: Uncaught Error: Class 'Automattic\WooCommerce\Client' not found in /var/www/webroot/ROOT/wp-content/plugins/woocommerce-external-product-embed-master/classes/class-wcepe-api-client.php:35 Stack trace: #0 /var/www/webroot/ROOT/wp-content/plugins/woocommerce-external-product-embed-master/classes/class-wcepe-api-client.php(63): WCEPE_API_Client->connect() #1 /var/www/webroot/ROOT/wp-content/plugins/woocommerce-external-product-embed-master/classes/class-wcepe-data-store.php(65): WCEPE_API_Client->get_products(Array) #2 /var/www/webroot/ROOT/wp-content/plugins/woocommerce-external-product-embed-master/classes/class-wcepe-data-store.php(56): WCEPE_Data_Store->save_loop_products() #3 /var/www/webroot/ROOT/wp-content/plugins/woocommerce-external-product-embed-master/classes/class-wcepe-shortcodes.php(84): WCEPE_Data_Store->get_loop_products() #4 /var/www/webroot/ROOT/wp-content/plugins/woocommerce-external-product-embed-master/classes/class-wcepe-shortcodes.php(195): WCEPE_Shortcodes::product_loop(Array, Array) #5 / in /var/www/webroot/ROOT/wp-content/plugins/woocommerce-external-product-embed-master/classes/class-wcepe-api-client.php on line 35`

**Comment by WPprodigy** [comment]
If you've downloaded directly from the GH master branch, then you'll need to run composer: https://github.com/WPprodigy/woocommerce-external-product-embed#development

Otherwise, you can download an already-built copy from the releases tab: https://github.com/WPprodigy/woocommerce-external-product-embed#installation
